name = "SASLib"
uuid = "df8f2f22-cfef-5733-af3f-96770d497d85"
authors = ["Tom Kwong <tk3369@gmail.com>"]
version = "1.0.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"
TabularDisplay = "3eeacb1d-13c2-54cc-9b18-30c86af3cadb"

[compat]
StringEncodings = "0.3"
TabularDisplay = "1"
julia = "1"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Statistics", "InteractiveUtils", "Printf", "SharedArrays"]
